<?php

use Illuminate\Database\Seeder;
use App\Municipios;

class Muni extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $municipio = new Municipios();

        $municipio->municipios = "AHUALULCO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "ALAQUINES";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "AQUISÓN";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "ARMADILLO DE LOS INFANTE";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CÁRDENAS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CATORCE";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CEDRAL";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CERRITOS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CERRO DE SAN PEDRO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CIUDAD DEL MAÍZ";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CIUDAD FERNÁNDEZ";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TANCANHUITZ";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CIUDAD VALLES";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "COXCATLÁN";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "CHARCAS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "EBANO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "GUADALCÁZAR";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "HUEHUETLÁN";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "LAGUNILLAS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "MATEHUALA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "MEXQUITIC DE CARMONA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "MOCTEZUMA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "RAYÓN";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "RIOVERDE";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SALINAS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SAN ANTONIO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SAN CIRO DE ACOSTA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SAN LUIS POTOSÍ";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SAN MARTÍN CHALCHICUAUTLA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SAN NICOLÁS TOLENTINO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SANTA CATARINA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SANTA MARÍA DEL RÍO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SANTO DOMINGO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SAN VICENTE TANCUAYALAB";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "SOLEDAD DE GRACIANO SÁNCHEZ";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TAMASOPO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TAMAZUNCHALE";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TAMPACÁN";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TAMPAMOLÓN CORONA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TAMUÍN";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "AQUISMÓN";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TANLAJÁS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TANQUIÁN DE ESCOBEDO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "TIERRA NUEVA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VANEGAS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VENADO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VILLA DE ARRIAGA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VILLA DE GUADALUPE";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VILLA DE LA PAZ";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VILLA DE RAMOS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VILLA DE REYES";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VILLA HIDALGO";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VILLA JUÁREZ";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "AXTLA DE TERRAZAS";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "XILITLA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "ZARAGOZA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "VILLA DE ARISTA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "MATLAPA";
        $municipio->save();
        $municipio = new Municipios();
        $municipio->municipios = "EL NARANJO";
        $municipio->save();
    }
}
